### ISSUE TITLE
Update for 0.8.X

### ISSUE THREAD

**Issue by ravingdragoon** [CeaneC/FoundryVTT-Ranger-Fog#3]
Can you please update this module for compatibility with Foundry 0.8.X?

**Comment by CeaneC** [comment]
Sure thing. If you've tried it, have you noticed any bugs that would need fixing? From my own testing it seems that the 0.8 upgrade didn't break anything, so it would just need the compatibility bump.

**Comment by ravingdragoon** [comment]
It could be that I have other modules enabled, but once fog was cleared for someone set as a ranger I was not able to unclear it without uninstalling the module. I dragged one PC as the GM and it went through all the walls and they were then able to see everything as explored, even if I reset the fog. I am using Foundry 0.8.9 and Chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Comment by CeaneC** [comment]
Hmm, I don't think I'm getting the same issue you are. Here's a screen recording of how it works on my end, with the following settings:
Scene - Fog Exploration enabled
Ranger Fog - Enabled for GM and Player
Modules - Only libWrapper, Ranger Fog, and TinyUI.

https://user-images.githubusercontent.com/43473593/131103900-5dee03b8-a336-48c6-b0bf-df4e40e80643.mp4

Could you try and replicate the issue with no other modules (other than libWrapper) enabled?

**Comment by ravingdragoon** [comment]
Ok, so with only the two modules and Find the Culprit enabled, the module doesn't seem to do anything at all.


https://user-images.githubusercontent.com/72875320/131193518-6d493941-9209-4e25-ae0e-5984b6c617fb.mp4

**Comment by CeaneC** [comment]
I tested with Find the Culprit as well (just to see if there was a conflict with that) and unfortunately couldn't replicate your issue. Have you double checked that Fog Exploration is enabled for the scene and that you've enabled exploration for yourself in the module settings?

![image](https://user-images.githubusercontent.com/43473593/131204096-77f796ea-cb88-4e16-be04-2ec39304a114.png)

**Comment by ravingdragoon** [comment]
Unfortunately, yes I have double checked both of those. What is very odd is that check with just Ranger Fog, libWrapper, and FtC, the module isn't working at all with all mods enabled either. It looks like you are using Brave browser, have you tried in Chrome?

**Comment by ravingdragoon** [comment]
Ok. I was able to mostly resolve the issue for now by completely removing and reinstalling your mod.

**Comment by CeaneC** [comment]
Glad you got it working! I did try on the same Chrome build that you were using but also couldn't replicate it. Hopefully next time a bug pops up it's easier to diagnose
