### ISSUE TITLE
V10 Compatibility?

### ISSUE THREAD

**Issue by Berytak** [CeaneC/FoundryVTT-Ranger-Fog#5]
Is there a plan to update this for v10? I would hate to give up this module, because it gave so much flavour to my sessions :(

**Comment by CeaneC** [comment]
I do plan to update it to V10, I just haven't gotten around to it as I've been busy (and I'm still on V9 myself). Once I update to V10 and get some time I'll be sure to take a look at adding V10 support

**Comment by Berytak** [comment]
It's awesome hear that you are planning to update your module. Out of my 96 installed modules, there are only 3 left without an update to v10, so I will gladly wait for that before switching to v10 myself.
Thank you very much for your afford!

**Comment by CeaneC** [comment]
V10 support has been added, let me know if there are any issues
