### ISSUE TITLE
Spammy compatibility warnings

### ISSUE THREAD

**Issue by dineshm72** [CeaneC/FoundryVTT-Ranger-Fog#8]
In v11 (and probably since v10) Ranger Fog is very spammy with the following warnings.  You get one every time a new token is selected, and multiple copies every time a token moves.  Ideally this can be corrected.

<img width="523" alt="image" src="https://github.com/CeaneC/FoundryVTT-Ranger-Fog/assets/2231877/3f4f82c8-0ea2-4378-bc06-60202f00441a">

**Comment by CeaneC** [comment]
Should be fixed in 2.0.2
